### ISSUE TITLE
translating the R1999 calculator into EN?

### ISSUE THREAD

**Issue by ninjakai03** [orz-tools/cpp#8]
hello! ive been using the calculator for Reverse 1999 for a bit now, and im curious if theres any way i could try translating the site into english for convenience?

**Comment by orzFly** [comment]
Sorry for the late reply. I apologize, but I don't have enough time to maintain the data for the R:1999, including the data for the Chinese server.

Firstly, there are no data-mining (including the Chinese server and others) publicly on the internet, and I don't have the energy and ability to maintain data-mining long-term.

Secondly, there is no structured drop data available. Moreover, the existing data will become outdated after version 1.4 due to the introduction of new stages. I don't have enough energy to maintain this data either.

**Help is greatly appreciated** in addressing these two issues. If the issues with data-mining and drop data can be effectively resolved, I would be happy to contribute to the i18n development of Closure++ itself.

**Comment by VenatusSimpleX** [comment]
Hi @orzFly, I am wondering if this spreadsheet is useful for your purposes, a person farmed each stage for 1000 times in global version of the game to determine the drop rate and efficiency for the stages, 1.4 stages are currently ongoing process for him.

[Spreadsheet](https://docs.google.com/spreadsheets/d/1GZMH5rJIqIUIh--MW9ahWCn2ExNvttjWGhT1lP1d4XM/edit#gid=2075797160)

**Comment by orzFly** [comment]
@VenatusSimpleX Thank you for sharing the link. This will definitely work in some way. I will join the Discord later to explore how I can utilize the data.

**Comment by orzFly** [comment]
![image](https://github.com/orz-tools/cpp/assets/158528/e7e785d3-c2d3-49e6-80f2-9aa700d7f835)

Please find the newly added button for selecting game servers. This will impact stages, character names, and item names. Currently, drop rates are still using those from the China server.

Regarding the string localization in Closure++ itself, it will take some additional time for me to figure out the best approach.

cc @VenatusSimpleX I am not sure if you are watching this issue, so I decided to CC you :)

**Comment by orzFly** [comment]
en_US locale has been added. Please report any localization errors.
